# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Stream' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'MobileVLCKit'
  # Pods for Stream

  target 'StreamTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StreamUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
